/* nexlet-signed.js — signed paperwork returned by the tenant.
 *
 * WHY
 *
 * Everything else in this app files what the agency SENT. The service history
 * records a document going out; the e-signature flow records one signed in the
 * browser. Neither has anywhere to put the other half of a move-in: the paper a
 * tenant signs at the property and hands straight back.
 *
 * That paper is the strongest evidence in the file. A receipt signed at the door
 * proves delivery in a way an email cannot — an email proves it was sent, a
 * signature proves it was received. Meter readings countersigned on the day are
 * what stop a disputed opening bill. An alarm test record signed by the tenant
 * is the first thing asked for after a fire.
 *
 * THREE THINGS THE FIRST VERSION GOT WRONG, all found by looking at a real
 * signed pack rather than at the code that prints one.
 *
 * 1. The list was hand-written here and had already drifted from what the pack
 *    prints — separate rows for meters and keys, which the pack prints as one
 *    sheet. It is now DERIVED from the pack's own sheet registry, so adding a
 *    sheet there adds its slot here.
 *
 * 2. A "sheet" is not a page. The real pack ran to fourteen pages across six
 *    documents: the receipt over two, key terms over two, the prescribed
 *    information over four, a longer key terms over four. So the bundle upload
 *    records a PAGE RANGE per document — one scan, but someone opening the alarm
 *    record is told it is on page 5 rather than left to search fourteen pages.
 *
 * 3. The prescribed information gets signed in practice and belongs on the list
 *    as a document of its own, not as an afterthought.
 */
(function () {
  'use strict';

  const ST = () => { try { return (typeof S !== 'undefined' && S) ? S : {}; } catch (e) { return {}; } };
  const esc = s => String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  const escJs = s => String(s == null ? '' : s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  const dt = d => { try { return d && window.fmtDate ? window.fmtDate(d) : ''; } catch (e) { return ''; } };
  const REC = pid => (window.tenantRecFor ? window.tenantRecFor(pid) : null) || null;

  /* Why the signature matters, as against what the sheet is. The pack's own
     descriptions explain the printing; these explain the filing. */
  const WHY = {
    receipt:  'Signed at handover. Proof the tenant received the pack \u2014 stronger than an email, which only proves it was sent.',
    keyterms: 'Signed confirmation the key terms were given and explained.',
    alarms:   'Tested in the tenant\u2019s presence on the first day of the tenancy, and signed. The first thing asked for after a fire.',
    meters:   'Countersigned readings and key count. What stops a disputed opening bill, and what proves how many keys went out.'
  };

  /* Signed paper that does not come off the move-in pack. The prescribed
     information is here rather than in the pack because it is generated by the
     deposit module, but it is signed as often as anything in the pack. */
  const EXTRAS = [
    ['deposit',   'Prescribed information \u2014 signed', 1,
     'Signed by the tenant on the scheme\u2019s own template. Not required, but it ends any argument about whether they received it.'],
    ['inventory', 'Inventory \u2014 signed schedule of condition', 0,
     'Where the tenant signed a paper copy rather than reviewing it online.'],
    ['standing',  'Standing order mandate', 0, ''],
    ['other',     'Other signed paperwork', 0, '']
  ];
  /* Only if the pack module has not loaded, so the shelf still works alone. */
  const FALLBACK = [['receipt', 'Receipt of documents', 1], ['keyterms', 'Written key terms', 1],
    ['alarms', 'Alarm test record', 1], ['meters', 'Meter readings and keys', 1]];

  function docs() {
    const sheets = (window.NexLetMoveIn && window.NexLetMoveIn.SHEETS)
      ? window.NexLetMoveIn.SHEETS.filter(s => s[3]).map(s => [s[0], s[1], 1, WHY[s[0]] || ''])
      : FALLBACK.map(s => [s[0], s[1], 1, WHY[s[0]] || '']);
    return sheets.concat(EXTRAS);
  }

  /* _printed is the pack's note of what went on paper, kept in the same bag. It
     is not a document and must never be counted as one. */
  const bag = rec => { const b = Object.assign({}, (rec && rec.signedDocs) || {}); delete b._printed; return b; };
  function held(pidOrRec, k) {
    const rec = (pidOrRec && pidOrRec.id) ? pidOrRec : REC(pidOrRec);
    return bag(rec)[k] || null;
  }
  function count(pid) {
    const rec = REC(pid); if (!rec) return { held: 0, core: 0, coreHeld: 0, printedUnscanned: 0 };
    const b = bag(rec), core = docs().filter(d => d[2]);
    const pr = (window.NexLetMoveIn && window.NexLetMoveIn.printedMap) ? window.NexLetMoveIn.printedMap(pid) : {};
    return { held: Object.keys(b).length, core: core.length,
      coreHeld: core.filter(d => b[d[0]]).length,
      printedUnscanned: core.filter(d => pr[d[0]] && !b[d[0]]).length };
  }
  const mb = n => (n / 1048576).toFixed(1) + ' MB';

  /* A phone photograph of one sheet is often larger than a fourteen-page scan,
     and none of that resolution survives being read on screen. Images are
     resized; a PDF cannot be, and goes up as it is. */
  /* Returns {blob, ext}. A resize always produces JPEG, so the stored name has to
     say .jpg — keeping a .heic or .png extension on JPEG bytes is the kind of
     mismatch that works until something downstream trusts the extension. */
  async function prepare(file) {
    const own = (file.name || '').split('.').pop() || 'pdf';
    if (!/^image\//.test(file.type || '') || !window._resizeImg) return { blob: file, ext: own };
    try {
      const b = await window._resizeImg(file, 1600);
      return (b && b.size < file.size) ? { blob: b, ext: 'jpg' } : { blob: file, ext: own };
    } catch (e) { return { blob: file, ext: own }; }
  }

  /* A 6 MB scan on a slow upstream takes a minute, and a button that has said
     "Filing…" for forty seconds is indistinguishable from a dead one. */
  function ticker(btn, verb, bytes) {
    if (!btn) return () => {};
    const t0 = Date.now();
    const size = bytes ? ' \u00b7 ' + mb(bytes) : '';
    const id = setInterval(() => {
      btn.textContent = verb + '\u2026 ' + Math.round((Date.now() - t0) / 1000) + 's' + size;
    }, 1000);
    btn.textContent = verb + '\u2026' + size;
    return () => clearInterval(id);
  }

  /* ── One document at a time ────────────────────────────────────────────── */
  function add(pid, key) {
    const rec = REC(pid); if (!rec) { window.toast('No tenancy on this property', 1); return; }
    const d = docs().find(x => x[0] === key) || ['other', 'Signed paperwork', 0, ''];
    const cur = held(rec, key);
    const today = new Date().toISOString().slice(0, 10);
    window.modal((cur ? 'Replace \u2014 ' : 'Attach \u2014 ') + esc(d[1]),
      (d[3] ? '<p class="hint" style="margin:0 0 12px">' + esc(d[3]) + '</p>' : '') +
      (cur ? '<div class="note" style="margin-bottom:12px">On file: <b>' + esc(cur.name) + '</b>, signed ' +
        esc(dt(cur.signedAt)) + '. Uploading again replaces it.</div>' : '') +
      (key === 'other' ? '<div class="fg"><label>What is it?</label>' +
        '<input id="sd-label" value="' + esc(cur ? cur.label || '' : '') + '" placeholder="e.g. Pet agreement"></div>' : '') +
      '<div class="fg"><label>Date it was signed <span class="faint">(not today\u2019s date, unless it was today)</span></label>' +
      '<input id="sd-date" type="date" max="' + today + '" value="' + esc(cur ? cur.signedAt : today) + '"></div>' +
      '<div class="hint" style="margin:-8px 0 12px">This is the date the evidence speaks to. A receipt signed on ' +
      'the day of the move proves service on that day, whenever you got round to scanning it.</div>' +
      '<div class="fg"><label>Who signed it <span class="faint">(optional)</span></label>' +
      '<input id="sd-by" value="' + esc(cur ? cur.by || '' : (rec.name || '')) + '"></div>' +
      '<div class="fg"><label>The scan or photograph</label>' +
      '<input id="sd-file" type="file" accept=".pdf,.png,.jpg,.jpeg,.heic" onchange="NexLetSigned.noteSize(this,\'sd-size\')">' +
      '<span class="hint" id="sd-size">A phone photograph is fine provided the signature and the date are legible.</span></div>',
      '<button class="btn" onclick="closeModal()">Cancel</button>' +
      (cur ? '<button class="btn" onclick="NexLetSigned.remove(\'' + escJs(pid) + '\',\'' + escJs(key) + '\')">Remove</button>' : '') +
      '<button class="btn navy" id="sd-save" onclick="NexLetSigned.save(\'' + escJs(pid) + '\',\'' + escJs(key) + '\')">Save</button>', true);
  }

  async function save(pid, key) {
    const rec = REC(pid); if (!rec) return;
    const el = id => document.getElementById(id);
    const fEl = el('sd-file'), file = fEl && fEl.files && fEl.files[0] ? fEl.files[0] : null;
    const cur = held(rec, key);
    if (!file && !cur) { window.toast('Attach the scan', 1); return; }
    const signedAt = (el('sd-date') || {}).value || '';
    if (!signedAt) { window.toast('Set the date it was signed', 1); return; }
    if (new Date(signedAt) > new Date()) { window.toast('That date is in the future', 1); return; }
    const btn = el('sd-save'); if (btn) btn.disabled = true;
    let stop = ticker(btn, 'Saving');

    let url = cur ? cur.url : '', name = cur ? cur.name : '';
    if (file) {
      if (!window._storageUpload) { stop(); window.toast('Cannot upload while offline \u2014 connect and try again', 1);
        if (btn) { btn.disabled = false; btn.textContent = 'Save'; } return; }
      const up = await prepare(file);
      stop(); stop = ticker(btn, 'Uploading', up.blob.size);
      url = await window._storageUpload(up.blob, pid + '/signed-' + key + '-' + Date.now() + '.' + up.ext, 'tenant-documents') || '';
      stop(); stop = ticker(btn, 'Saving');
      /* An upload that failed must not leave a row claiming a copy is on file. A
         missing document you know about is recoverable; one you believe you have
         is not. */
      if (!url) { stop(); window.toast('\u26a0 It did not upload \u2014 nothing saved. Check your connection.', 1);
        if (btn) { btn.disabled = false; btn.textContent = 'Save'; } return; }
      name = file.name;
    }
    /* Kept so the mutation can be undone if the write fails. The audit trail is
       append-only and hash-chained: an entry saying a signed document was filed
       cannot be withdrawn later, so it must not be written until the row it
       describes actually exists. Same rule the storage path already follows. */
    const before = rec.signedDocs;
    rec.signedDocs = Object.assign({}, rec.signedDocs || {});
    rec.signedDocs[key] = { url: url, name: name, signedAt: signedAt,
      by: (el('sd-by') || {}).value || '', label: (el('sd-label') || {}).value || '',
      addedAt: new Date().toISOString() };
    if (window.save) window.save();
    if (window.pushTenantRec && !(await window.pushTenantRec(rec))) {
      rec.signedDocs = before; stop();
      if (btn) { btn.disabled = false; btn.textContent = 'Save'; }
      return;   /* pushTenantRec has already toasted why */
    }
    stop();
    if (window.NexLetAudit) window.NexLetAudit.log({ action: 'signed.filed', entity: 'tenancy',
      entityId: rec.id, entityLabel: ((window.P && window.P(pid)) || {}).address || '',
      detail: { document: (docs().find(x => x[0] === key) || [])[1] || key, signedAt: signedAt } });
    window.closeModal(); if (window.render) window.render();
    window.toast('\u2713 Filed \u2014 signed ' + dt(signedAt));
  }

  async function remove(pid, key) {
    const rec = REC(pid); if (!rec || !rec.signedDocs) return;
    const before = rec.signedDocs;
    const b = Object.assign({}, rec.signedDocs); delete b[key];
    rec.signedDocs = b;
    if (window.save) window.save();
    if (window.pushTenantRec && !(await window.pushTenantRec(rec))) { rec.signedDocs = before; return; }
    window.closeModal(); if (window.render) window.render();
    window.toast('Removed from the shelf');
  }

  /* ── One scan covering several documents ───────────────────────────────── */
  /* A move-in produces a stack signed in one sitting, and most agents scan the
     stack in one pass. Making them split it into separate files to satisfy the
     app would be the app's problem imposed on the user. So a single upload can
     cover several documents: stored once, with a page range per document, which
     is what makes a fourteen-page bundle usable as evidence rather than a pile
     someone has to read through. */
  function addBundle(pid) {
    const rec = REC(pid); if (!rec) { window.toast('No tenancy on this property', 1); return; }
    const today = new Date().toISOString().slice(0, 10);
    window.modal('One scan covering several documents',
      '<p class="hint" style="margin:0 0 12px">For the usual case: the whole signed stack scanned in one pass. It ' +
      'is stored once and listed against everything it contains. Give each document its page numbers if you can \u2014 ' +
      'a fourteen-page bundle is only useful if someone can find the alarm record in it.</p>' +
      '<div class="grid2" style="gap:10px">' +
      '<div class="fg"><label>Date they were signed</label>' +
      '<input id="sb-date" type="date" max="' + today + '" value="' + today + '"></div>' +
      '<div class="fg"><label>Who signed <span class="faint">(optional)</span></label>' +
      '<input id="sb-by" value="' + esc(rec.name || '') + '"></div></div>' +
      '<div class="fg"><label>What it contains</label>' +
      docs().filter(d => d[0] !== 'other').map(d =>
        '<div style="display:flex;gap:9px;align-items:center;padding:7px 0;border-top:1px solid var(--border)">' +
        '<input type="checkbox" class="sb-item" value="' + d[0] + '"' + (d[2] ? ' checked' : '') + ' style="width:auto;margin:0">' +
        '<span style="flex:1;min-width:0"><span style="font-size:12.5px;font-weight:600;color:var(--navy)">' + esc(d[1]) + '</span>' +
        (held(rec, d[0]) ? '<span class="faint" style="display:block;font-size:11px">Already on file \u2014 ticking replaces it</span>' : '') +
        '</span>' +
        '<input class="sb-pg" data-k="' + d[0] + '" placeholder="pages" style="width:82px;flex-shrink:0;font-size:12px">' +
        '</div>').join('') + '</div>' +
      '<div class="hint" style="margin:-6px 0 12px">Pages are optional and free text \u2014 "1\u20132", "5", "7\u201310".</div>' +
      '<div class="fg"><label>The scan</label>' +
      '<input id="sb-file" type="file" accept=".pdf,.png,.jpg,.jpeg,.heic" onchange="NexLetSigned.noteSize(this,\'sb-size\')">' +
      '<span class="hint" id="sb-size">One PDF of the whole stack, or a photograph if it is a single sheet.</span></div>',
      '<button class="btn" onclick="closeModal()">Cancel</button>' +
      '<button class="btn navy" id="sb-save" onclick="NexLetSigned.saveBundle(\'' + escJs(pid) + '\')">File it</button>', true);
  }

  async function saveBundle(pid) {
    const rec = REC(pid); if (!rec) return;
    const el = id => document.getElementById(id);
    const keys = [...document.querySelectorAll('.sb-item')].filter(x => x.checked).map(x => x.value);
    if (!keys.length) { window.toast('Tick what the scan contains', 1); return; }
    const fEl = el('sb-file'), file = fEl && fEl.files && fEl.files[0] ? fEl.files[0] : null;
    if (!file) { window.toast('Attach the scan', 1); return; }
    const signedAt = (el('sb-date') || {}).value || '';
    if (!signedAt) { window.toast('Set the date they were signed', 1); return; }
    if (new Date(signedAt) > new Date()) { window.toast('That date is in the future', 1); return; }
    const btn = el('sb-save'); if (btn) btn.disabled = true;
    let stop = ticker(btn, 'Filing');

    if (!window._storageUpload) { stop(); window.toast('Cannot upload while offline \u2014 connect and try again', 1);
      if (btn) { btn.disabled = false; btn.textContent = 'File it'; } return; }
    const pg = {};
    [...document.querySelectorAll('.sb-pg')].forEach(i => {
      const v = (i.value || '').trim(); if (v) pg[i.getAttribute('data-k')] = v;
    });
    const up = await prepare(file);
    stop(); stop = ticker(btn, 'Uploading', up.blob.size);
    /* Uploaded once. Every ticked document points at the same object rather than
       at its own copy — five copies of one bundle is five things to keep in step. */
    const url = await window._storageUpload(up.blob, pid + '/signed-bundle-' + Date.now() + '.' + up.ext, 'tenant-documents') || '';
    stop(); stop = ticker(btn, 'Filing');
    if (!url) { stop(); window.toast('\u26a0 It did not upload \u2014 nothing saved. Check your connection.', 1);
      if (btn) { btn.disabled = false; btn.textContent = 'File it'; } return; }

    const by = (el('sb-by') || {}).value || '';
    const before = rec.signedDocs;
    rec.signedDocs = Object.assign({}, rec.signedDocs || {});
    keys.forEach(k => { rec.signedDocs[k] = { url: url, name: file.name, signedAt: signedAt, by: by,
      bundle: true, pages: pg[k] || '', addedAt: new Date().toISOString() }; });
    if (window.save) window.save();
    if (window.pushTenantRec && !(await window.pushTenantRec(rec))) {
      rec.signedDocs = before; stop();
      if (btn) { btn.disabled = false; btn.textContent = 'File it'; }
      return;
    }
    stop();
    if (window.NexLetAudit) window.NexLetAudit.log({ action: 'signed.filed', entity: 'tenancy',
      entityId: rec.id, entityLabel: ((window.P && window.P(pid)) || {}).address || '',
      detail: { bundle: true, documents: keys.length, signedAt: signedAt } });
    window.closeModal(); if (window.render) window.render();
    window.toast('\u2713 Filed against ' + keys.length + ' document' + (keys.length === 1 ? '' : 's') + ' \u2014 signed ' + dt(signedAt));
  }

  /* The shelf's own panel is gone. Its three facts now live as columns on the
     document register, which is the whole point of the consolidation — leaving a
     second, unrendered document list here is exactly how six lists happened. The
     module remains as the store: the register, the move-in chooser and the
     landlord pack all read it.

     Callers: NexLetRegister (rows, backCell, extraSigned), NexLetMoveIn (pack
     chooser + printed state), NexLetServe (landlord attachments), and the
     move-in checklist in agent.html. */

  /* Called from the file inputs' onchange in add() and addBundle(). Lost once to
     a careless slice between two anchors when panel() was removed — the export
     below still named it, so the whole module failed to register and every
     signed document silently vanished from the register. */
  function noteSize(input, targetId) {
    const t = document.getElementById(targetId); if (!t) return;
    const f = input && input.files && input.files[0];
    if (!f) return;
    const big = f.size > 4 * 1048576;
    t.innerHTML = esc(f.name) + ' \u00b7 <b>' + mb(f.size) + '</b>' +
      (big ? ' \u2014 a file this size takes up to a minute to upload. The button will count the seconds; leave it running.'
           : /^image\//.test(f.type || '') ? ' \u2014 will be resized before uploading.' : '');
    t.style.color = big ? 'var(--amber)' : '';
  }

  window.NexLetSigned = { add, save, remove, addBundle, saveBundle, count, held, docs, noteSize };
})();
