/* nexlet-signed.js — signed paperwork returned by the tenant.
 *
 * WHY
 *
 * Everything else in this app files what the agency SENT. The service history
 * records a document going out; the e-signature flow records one signed in the
 * browser. Neither has anywhere to put the other half of a move-in: the paper a
 * tenant signs at the property and hands straight back.
 *
 * That paper is the strongest evidence in the file. A receipt signed at the door
 * proves delivery in a way an email cannot — an email proves it was sent, a
 * signature proves it was received. Meter readings countersigned on the day are
 * what stop a disputed opening bill. An alarm test record signed by the tenant
 * is the first thing asked for after a fire.
 *
 * THREE THINGS THE FIRST VERSION GOT WRONG, all found by looking at a real
 * signed pack rather than at the code that prints one.
 *
 * 1. The list was hand-written here and had already drifted from what the pack
 *    prints — separate rows for meters and keys, which the pack prints as one
 *    sheet. It is now DERIVED from the pack's own sheet registry, so adding a
 *    sheet there adds its slot here.
 *
 * 2. A "sheet" is not a page. The real pack ran to fourteen pages across six
 *    documents: the receipt over two, key terms over two, the prescribed
 *    information over four, a longer key terms over four. So the bundle upload
 *    records a PAGE RANGE per document — one scan, but someone opening the alarm
 *    record is told it is on page 5 rather than left to search fourteen pages.
 *
 * 3. The prescribed information gets signed in practice and belongs on the list
 *    as a document of its own, not as an afterthought.
 */
(function () {
  'use strict';

  const ST = () => { try { return (typeof S !== 'undefined' && S) ? S : {}; } catch (e) { return {}; } };
  const esc = s => String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  const escJs = s => String(s == null ? '' : s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  const dt = d => { try { return d && window.fmtDate ? window.fmtDate(d) : ''; } catch (e) { return ''; } };
  const REC = pid => (window.tenantRecFor ? window.tenantRecFor(pid) : null) || null;

  /* Why the signature matters, as against what the sheet is. The pack's own
     descriptions explain the printing; these explain the filing. */
  const WHY = {
    receipt:  'Signed at handover. Proof the tenant received the pack \u2014 stronger than an email, which only proves it was sent.',
    keyterms: 'Signed confirmation the key terms were given and explained.',
    alarms:   'Tested in the tenant\u2019s presence on the first day of the tenancy, and signed. The first thing asked for after a fire.',
    meters:   'Countersigned readings and key count. What stops a disputed opening bill, and what proves how many keys went out.'
  };

  /* Signed paper that does not come off the move-in pack. The prescribed
     information is here rather than in the pack because it is generated by the
     deposit module, but it is signed as often as anything in the pack. */
  const EXTRAS = [
    ['deposit',   'Prescribed information \u2014 signed', 1,
     'Signed by the tenant on the scheme\u2019s own template. Not required, but it ends any argument about whether they received it.'],
    ['inventory', 'Inventory \u2014 signed schedule of condition', 0,
     'Where the tenant signed a paper copy rather than reviewing it online.'],
    ['standing',  'Standing order mandate', 0, ''],
    ['other',     'Other signed paperwork', 0, '']
  ];
  /* Only if the pack module has not loaded, so the shelf still works alone. */
  const FALLBACK = [['receipt', 'Receipt of documents', 1], ['keyterms', 'Written key terms', 1],
    ['alarms', 'Alarm test record', 1], ['meters', 'Meter readings and keys', 1]];

  function docs() {
    const sheets = (window.NexLetMoveIn && window.NexLetMoveIn.SHEETS)
      ? window.NexLetMoveIn.SHEETS.filter(s => s[3]).map(s => [s[0], s[1], 1, WHY[s[0]] || ''])
      : FALLBACK.map(s => [s[0], s[1], 1, WHY[s[0]] || '']);
    return sheets.concat(EXTRAS);
  }

  /* _printed is the pack's note of what went on paper, kept in the same bag. It
     is not a document and must never be counted as one. */
  const bag = rec => { const b = Object.assign({}, (rec && rec.signedDocs) || {}); delete b._printed; return b; };
  function held(pidOrRec, k) {
    const rec = (pidOrRec && pidOrRec.id) ? pidOrRec : REC(pidOrRec);
    return bag(rec)[k] || null;
  }
  function count(pid) {
    const rec = REC(pid); if (!rec) return { held: 0, core: 0, coreHeld: 0, printedUnscanned: 0 };
    const b = bag(rec), core = docs().filter(d => d[2]);
    const pr = (window.NexLetMoveIn && window.NexLetMoveIn.printedMap) ? window.NexLetMoveIn.printedMap(pid) : {};
    return { held: Object.keys(b).length, core: core.length,
      coreHeld: core.filter(d => b[d[0]]).length,
      printedUnscanned: core.filter(d => pr[d[0]] && !b[d[0]]).length };
  }
  const pagesNote = h => (h && h.pages) ? ' \u00b7 p' + h.pages : '';

  /* ── One document at a time ────────────────────────────────────────────── */
  function add(pid, key) {
    const rec = REC(pid); if (!rec) { window.toast('No tenancy on this property', 1); return; }
    const d = docs().find(x => x[0] === key) || ['other', 'Signed paperwork', 0, ''];
    const cur = held(rec, key);
    const today = new Date().toISOString().slice(0, 10);
    window.modal((cur ? 'Replace \u2014 ' : 'Attach \u2014 ') + esc(d[1]),
      (d[3] ? '<p class="hint" style="margin:0 0 12px">' + esc(d[3]) + '</p>' : '') +
      (cur ? '<div class="note" style="margin-bottom:12px">On file: <b>' + esc(cur.name) + '</b>, signed ' +
        esc(dt(cur.signedAt)) + '. Uploading again replaces it.</div>' : '') +
      (key === 'other' ? '<div class="fg"><label>What is it?</label>' +
        '<input id="sd-label" value="' + esc(cur ? cur.label || '' : '') + '" placeholder="e.g. Pet agreement"></div>' : '') +
      '<div class="fg"><label>Date it was signed <span class="faint">(not today\u2019s date, unless it was today)</span></label>' +
      '<input id="sd-date" type="date" max="' + today + '" value="' + esc(cur ? cur.signedAt : today) + '"></div>' +
      '<div class="hint" style="margin:-8px 0 12px">This is the date the evidence speaks to. A receipt signed on ' +
      'the day of the move proves service on that day, whenever you got round to scanning it.</div>' +
      '<div class="fg"><label>Who signed it <span class="faint">(optional)</span></label>' +
      '<input id="sd-by" value="' + esc(cur ? cur.by || '' : (rec.name || '')) + '"></div>' +
      '<div class="fg"><label>The scan or photograph</label>' +
      '<input id="sd-file" type="file" accept=".pdf,.png,.jpg,.jpeg,.heic">' +
      '<span class="hint">A phone photograph is fine provided the signature and the date are legible.</span></div>',
      '<button class="btn" onclick="closeModal()">Cancel</button>' +
      (cur ? '<button class="btn" onclick="NexLetSigned.remove(\'' + escJs(pid) + '\',\'' + escJs(key) + '\')">Remove</button>' : '') +
      '<button class="btn navy" id="sd-save" onclick="NexLetSigned.save(\'' + escJs(pid) + '\',\'' + escJs(key) + '\')">Save</button>', true);
  }

  async function save(pid, key) {
    const rec = REC(pid); if (!rec) return;
    const el = id => document.getElementById(id);
    const fEl = el('sd-file'), file = fEl && fEl.files && fEl.files[0] ? fEl.files[0] : null;
    const cur = held(rec, key);
    if (!file && !cur) { window.toast('Attach the scan', 1); return; }
    const signedAt = (el('sd-date') || {}).value || '';
    if (!signedAt) { window.toast('Set the date it was signed', 1); return; }
    if (new Date(signedAt) > new Date()) { window.toast('That date is in the future', 1); return; }
    const btn = el('sd-save'); if (btn) { btn.disabled = true; btn.textContent = 'Saving\u2026'; }

    let url = cur ? cur.url : '', name = cur ? cur.name : '';
    if (file) {
      if (!window._storageUpload) { window.toast('Cannot upload while offline \u2014 connect and try again', 1); return; }
      const ext = (file.name.split('.').pop() || 'pdf');
      url = await window._storageUpload(file, pid + '/signed-' + key + '-' + Date.now() + '.' + ext, 'tenant-documents') || '';
      /* An upload that failed must not leave a row claiming a copy is on file. A
         missing document you know about is recoverable; one you believe you have
         is not. */
      if (!url) { window.toast('\u26a0 It did not upload \u2014 nothing saved. Check your connection.', 1);
        if (btn) { btn.disabled = false; btn.textContent = 'Save'; } return; }
      name = file.name;
    }
    rec.signedDocs = Object.assign({}, rec.signedDocs || {});
    rec.signedDocs[key] = { url: url, name: name, signedAt: signedAt,
      by: (el('sd-by') || {}).value || '', label: (el('sd-label') || {}).value || '',
      addedAt: new Date().toISOString() };
    if (window.save) window.save();
    if (window.pushTenantRec) await window.pushTenantRec(rec);
    if (window.NexLetAudit) window.NexLetAudit.log({ action: 'signed.filed', entity: 'tenancy',
      entityId: rec.id, entityLabel: ((window.P && window.P(pid)) || {}).address || '',
      detail: { document: (docs().find(x => x[0] === key) || [])[1] || key, signedAt: signedAt } });
    window.closeModal(); if (window.render) window.render();
    window.toast('\u2713 Filed \u2014 signed ' + dt(signedAt));
  }

  function remove(pid, key) {
    const rec = REC(pid); if (!rec || !rec.signedDocs) return;
    const b = Object.assign({}, rec.signedDocs); delete b[key];
    rec.signedDocs = b;
    if (window.save) window.save();
    if (window.pushTenantRec) window.pushTenantRec(rec);
    window.closeModal(); if (window.render) window.render();
    window.toast('Removed from the shelf');
  }

  /* ── One scan covering several documents ───────────────────────────────── */
  /* A move-in produces a stack signed in one sitting, and most agents scan the
     stack in one pass. Making them split it into separate files to satisfy the
     app would be the app's problem imposed on the user. So a single upload can
     cover several documents: stored once, with a page range per document, which
     is what makes a fourteen-page bundle usable as evidence rather than a pile
     someone has to read through. */
  function addBundle(pid) {
    const rec = REC(pid); if (!rec) { window.toast('No tenancy on this property', 1); return; }
    const today = new Date().toISOString().slice(0, 10);
    window.modal('One scan covering several documents',
      '<p class="hint" style="margin:0 0 12px">For the usual case: the whole signed stack scanned in one pass. It ' +
      'is stored once and listed against everything it contains. Give each document its page numbers if you can \u2014 ' +
      'a fourteen-page bundle is only useful if someone can find the alarm record in it.</p>' +
      '<div class="grid2" style="gap:10px">' +
      '<div class="fg"><label>Date they were signed</label>' +
      '<input id="sb-date" type="date" max="' + today + '" value="' + today + '"></div>' +
      '<div class="fg"><label>Who signed <span class="faint">(optional)</span></label>' +
      '<input id="sb-by" value="' + esc(rec.name || '') + '"></div></div>' +
      '<div class="fg"><label>What it contains</label>' +
      docs().filter(d => d[0] !== 'other').map(d =>
        '<div style="display:flex;gap:9px;align-items:center;padding:7px 0;border-top:1px solid var(--border)">' +
        '<input type="checkbox" class="sb-item" value="' + d[0] + '"' + (d[2] ? ' checked' : '') + ' style="width:auto;margin:0">' +
        '<span style="flex:1;min-width:0"><span style="font-size:12.5px;font-weight:600;color:var(--navy)">' + esc(d[1]) + '</span>' +
        (held(rec, d[0]) ? '<span class="faint" style="display:block;font-size:11px">Already on file \u2014 ticking replaces it</span>' : '') +
        '</span>' +
        '<input class="sb-pg" data-k="' + d[0] + '" placeholder="pages" style="width:82px;flex-shrink:0;font-size:12px">' +
        '</div>').join('') + '</div>' +
      '<div class="hint" style="margin:-6px 0 12px">Pages are optional and free text \u2014 "1\u20132", "5", "7\u201310".</div>' +
      '<div class="fg"><label>The scan</label>' +
      '<input id="sb-file" type="file" accept=".pdf,.png,.jpg,.jpeg,.heic">' +
      '<span class="hint">One PDF of the whole stack, or a photograph if it is a single sheet.</span></div>',
      '<button class="btn" onclick="closeModal()">Cancel</button>' +
      '<button class="btn navy" id="sb-save" onclick="NexLetSigned.saveBundle(\'' + escJs(pid) + '\')">File it</button>', true);
  }

  async function saveBundle(pid) {
    const rec = REC(pid); if (!rec) return;
    const el = id => document.getElementById(id);
    const keys = [...document.querySelectorAll('.sb-item')].filter(x => x.checked).map(x => x.value);
    if (!keys.length) { window.toast('Tick what the scan contains', 1); return; }
    const fEl = el('sb-file'), file = fEl && fEl.files && fEl.files[0] ? fEl.files[0] : null;
    if (!file) { window.toast('Attach the scan', 1); return; }
    const signedAt = (el('sb-date') || {}).value || '';
    if (!signedAt) { window.toast('Set the date they were signed', 1); return; }
    if (new Date(signedAt) > new Date()) { window.toast('That date is in the future', 1); return; }
    const btn = el('sb-save'); if (btn) { btn.disabled = true; btn.textContent = 'Filing\u2026'; }

    if (!window._storageUpload) { window.toast('Cannot upload while offline \u2014 connect and try again', 1); return; }
    const pg = {};
    [...document.querySelectorAll('.sb-pg')].forEach(i => {
      const v = (i.value || '').trim(); if (v) pg[i.getAttribute('data-k')] = v;
    });
    const ext = (file.name.split('.').pop() || 'pdf');
    /* Uploaded once. Every ticked document points at the same object rather than
       at its own copy — five copies of one bundle is five things to keep in step. */
    const url = await window._storageUpload(file, pid + '/signed-bundle-' + Date.now() + '.' + ext, 'tenant-documents') || '';
    if (!url) { window.toast('\u26a0 It did not upload \u2014 nothing saved. Check your connection.', 1);
      if (btn) { btn.disabled = false; btn.textContent = 'File it'; } return; }

    const by = (el('sb-by') || {}).value || '';
    rec.signedDocs = Object.assign({}, rec.signedDocs || {});
    keys.forEach(k => { rec.signedDocs[k] = { url: url, name: file.name, signedAt: signedAt, by: by,
      bundle: true, pages: pg[k] || '', addedAt: new Date().toISOString() }; });
    if (window.save) window.save();
    if (window.pushTenantRec) await window.pushTenantRec(rec);
    if (window.NexLetAudit) window.NexLetAudit.log({ action: 'signed.filed', entity: 'tenancy',
      entityId: rec.id, entityLabel: ((window.P && window.P(pid)) || {}).address || '',
      detail: { bundle: true, documents: keys.length, signedAt: signedAt } });
    window.closeModal(); if (window.render) window.render();
    window.toast('\u2713 Filed against ' + keys.length + ' document' + (keys.length === 1 ? '' : 's') + ' \u2014 signed ' + dt(signedAt));
  }

  /* ── Panel ─────────────────────────────────────────────────────────────── */
  function panel(pid) {
    const rec = REC(pid); if (!rec || !rec.id) return '';
    const c = count(pid);
    const pr = (window.NexLetMoveIn && window.NexLetMoveIn.printedMap) ? window.NexLetMoveIn.printedMap(pid) : {};
    const row = d => {
      const h = held(rec, d[0]);
      const label = (d[0] === 'other' && h && h.label) ? h.label : d[1];
      const state = h
        ? 'Signed ' + esc(dt(h.signedAt)) + (h.by ? ' by ' + esc(h.by) : '') + pagesNote(h) +
          (h.bundle ? ' <span style="color:var(--muted)">\u00b7 in the combined scan</span>' : ' \u00b7 ' + esc(h.name))
        : (d[2] && pr[d[0]]) ? '<span style="color:var(--amber)">Printed ' + esc(dt(pr[d[0]])) + ' \u00b7 not scanned back</span>'
        : (d[2] ? 'Not on file' : 'Not on file \u2014 only if it applies');
      return '<div class="row" style="align-items:flex-start">' +
        '<span style="width:19px;flex-shrink:0;color:' + (h ? 'var(--green)' : (d[2] ? 'var(--amber)' : 'var(--faint)')) +
        ';font-weight:700">' + (h ? '\u2713' : '\u25cb') + '</span>' +
        '<div style="flex:1;min-width:0">' +
        '<div style="font-size:13px;font-weight:600;color:' + (h ? 'var(--navy)' : 'var(--muted)') + '">' + esc(label) + '</div>' +
        '<div class="faint" style="font-size:11.5px;margin-top:2px">' + state + '</div></div>' +
        '<div style="display:flex;gap:6px;flex-shrink:0">' +
        (h ? '<button class="btn sm" onclick="viewDoc(\'' + escJs(h.url) + '\',\'' + escJs(label) + '\')">View</button>' : '') +
        '<button class="btn sm' + (h ? '' : ' navy') + '" onclick="NexLetSigned.add(\'' + escJs(pid) + '\',\'' + escJs(d[0]) + '\')">' +
        (h ? 'Replace' : 'Attach') + '</button></div></div>';
    };
    const missing = c.core - c.coreHeld;
    return '<div class="panel" style="margin-bottom:14px"><div class="panel-hd"><h2>Signed paperwork on file</h2>' +
      '<span class="faint" style="font-size:12px">' + c.coreHeld + ' of ' + c.core + ' key documents</span></div>' +
      '<div class="panel-bd">' +
      '<div class="hint" style="margin:0 0 10px">What the tenant signed and handed back. The rest of this page ' +
      'records what you <i>sent</i>; a signature proves it was <i>received</i>, which is the harder thing to show.</div>' +
      (c.printedUnscanned
        ? '<div class="note warn" style="margin-bottom:10px"><b>' + c.printedUnscanned + ' printed and not scanned back.</b> ' +
          'Paper on a desk is not evidence until it is on the file.</div>'
        : missing ? '<div class="note warn" style="margin-bottom:10px"><b>' + missing + ' still to scan.</b></div>' : '') +
      docs().map(row).join('') +
      '<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px">' +
      '<button class="btn sm navy" onclick="NexLetSigned.addBundle(\'' + escJs(pid) + '\')">' +
      '\u2191 Upload one scan of the whole stack</button></div>' +
      '</div></div>';
  }

  window.NexLetSigned = { panel, add, save, remove, addBundle, saveBundle, count, held, docs };
})();
